/**
 * Film / TV-program / TV-series class sets, generated by scripts/screen-classes.ts
 * (a one-off SPARQL P279* walk per root) and checked in. Never walked at request time:
 * the walk is slow and the sets change rarely. Regenerate when Wikidata reclassifies.
 */
import classes from './screenClasses.json';

export type ScreenKind = 'film' | 'tv';

export const FILM_CLASSES: ReadonlySet<string> = new Set(classes.film);
export const TV_PROGRAM_CLASSES: ReadonlySet<string> = new Set(classes.tv_program);
export const TV_SERIES_CLASSES: ReadonlySet<string> = new Set(classes.tv_series);

/** Spike resolve3.py: 'film' if any P31 is a film class, else 'tv' if a TV-program class. */
export function classifyP31(p31: readonly string[]): ScreenKind | null {
  if (p31.some((c) => FILM_CLASSES.has(c))) return 'film';
  if (p31.some((c) => TV_PROGRAM_CLASSES.has(c))) return 'tv';
  return null;
}

/** A subclass of Q5398426 -- the only kind of TV item that converts to media_type 'tv'. */
export function isTvSeries(p31: readonly string[]): boolean {
  return p31.some((c) => TV_SERIES_CLASSES.has(c));
}
